name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upgrade pip
      run: pip install --constraint=.github/workflows/constraints.txt pip

    - name: Install Poetry
      run: pip install --constraint=.github/workflows/constraints.txt poetry
      
    - name: Install Nox
      run: pip install --constraint=.github/workflows/constraints.txt nox

    - name: Install nox-poetry
      run: pip install --constraint=.github/workflows/constraints.txt nox-poetry

    - name: Set up Nox
      uses: excitedleigh/setup-nox@v2.0.0

    - name: Install Poetry
      uses: snok/install-poetry@v1.1.3

    - name: Run Nox
      run: nox

    - name: Build with Poetry
      run: poetry build

    - name: Publish to PyPI
      run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
